### ISSUE TITLE
Getting error while sending mail using SES

### ISSUE THREAD

**Issue by Ashesh007** [andris9/nodemailer-ses-transport#11]
{ [SignatureDoesNotMatch: The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.

The Canonical String for this request should have been
'POST
/

host:email.us-east-1.amazonaws.com
x-amz-content-sha256:a7af6154cbe7228819ca5370c7dfd43ebdfc87f3291ec5d55d00f7b9486e39e4
x-amz-date:20151008T084042Z

host;x-amz-content-sha256;x-amz-date
a7af6154cbe7228819ca5370c7dfd43ebdfc87f3291ec5d55d00f7b9486e39e4'

The String-to-Sign should have been
'AWS4-HMAC-SHA256
20151008T084042Z
20151008/us-east-1/ses/aws4_request
8b08f864033d5cc35c70ba6aed99bf26646e26601674fa52fa666532d3910f05'
]
  message: 'The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.\n\nThe Canonical String for this request should have been\n\'POST\n/\n\nhost:email.us-east-1.amazonaws.com\nx-amz-content-sha256:a7af6154cbe7228819ca5370c7dfd43ebdfc87f3291ec5d55d00f7b9486e39e4\nx-amz-date:20151008T084042Z\n\nhost;x-amz-content-sha256;x-amz-date\na7af6154cbe7228819ca5370c7dfd43ebdfc87f3291ec5d55d00f7b9486e39e4\'\n\nThe String-to-Sign should have been\n\'AWS4-HMAC-SHA256\n20151008T084042Z\n20151008/us-east-1/ses/aws4_request\n8b08f864033d5cc35c70ba6aed99bf26646e26601674fa52fa666532d3910f05\'\n',
  code: 'SignatureDoesNotMatch',
  time: Thu Oct 08 2015 14:10:43 GMT+0530 (IST),
  statusCode: 403,
  retryable: false,
  retryDelay: 30 }
Getting above error while using amazon sns service for mailing,
and while this secretKey and accestokenkey used in PHP its working. then what should i have to do??

**Comment by sajayi** [comment]
Hi @Ashesh007, Just got this error too. Have you been able to fix it?

**Comment by ahopper-soltech** [comment]
+1; we're also seeing this.

**Comment by sajayi** [comment]
I think I found that this can be resolved by manually creating the IAM user from IAM console  and assigning rights to access SES rather than from SES Console.

**Comment by andris9** [comment]
Yes, this issue is related to proper aws tokens and not with nodemailer-ses-transport.
