### ISSUE TITLE
queue limit of 10?

### ISSUE THREAD

**Issue by youjying** [andris9/nodemailer-ses-transport#12]
I set my send limit to 14 email/sec. Yet, when I loop through and try to send 50 or so emails, only 10 ever get through. I never get an error. Amazon even says only 10 emails were sent. I got indexes 0-9 in my email inbox. I log to my console all 50 of them calling the sendmail function. But only 10 callbacks occur.

essentially what I'm using:
emails.forEach(function(email, index){
console.log(email);
var mailOptions = {
	from: 'no-reply@gmail.com',
	 to: email, 
        subject: 'Hello ',
        text: 'test ' + index,
};
transporter.sendMail(mailOptions, function(error, info) {
       if (error) {
	     return console.log(error);
       }
	console.log(info);
});
)};

**Comment by knightcode** [comment]
Also have rateLimit set to 14. Our weekly promo mailer just went out way too fast, and we got a bunch of "Maximum sending rat exceeded" errors. I haven't changed anything since the last time, and this is the first time it's happened.

**Comment by massimocode** [comment]
I think this issue has been fixed with this PR https://github.com/andris9/nodemailer-ses-transport/pull/18. If we re-release to NPM then we can close this issue.
