### ISSUE TITLE
Question about queue handling

### ISSUE THREAD

**Issue by scriby** [andris9/nodemailer-ses-transport#15]
I was trying to read the queue handling code after looking at issue #12. It's a little difficult to follow because each call to queue a message ends up "looping" until it can get sent.

If I am understanding it correctly, then I think it may cause messages to not always get sent in the order they are queued. I think there's two scenarios:

* When processQueue allows a message to go through, it uses `setImmediate(this.processQueue.bind(this));`. However, before that processQueue call executes, another call to processQueue could have come in on another execution context, and when it enters the processQueue method it will see this.sending is false and get sent instead of the intended message.

* Let's say we queue 10 messages at once and the rateLimit is 10. The first one will get sent, and the second message will schedule a timeout to get sent in 100ms, the third message after 200ms, up to the 10th message after 900ms. At the point the second message is sent, this.count is reset back to 0. Now, let's say another message is queued at this point, it will get queued to send in 100ms because count is 1 again. So the new message that was queued will end up getting sent before most of the originally queued messages.

I think the simplest approach would be to just write a single queue processor that just dequeues a message, sends it, then sleeps 1000 / rateLimit ms and repeats until there are no messages left to send. Adding more unit tests around rate limit behavior would also not be bad.

**Comment by massimocode** [comment]
I think this issue has been fixed with this PR https://github.com/andris9/nodemailer-ses-transport/pull/18. We can probably close this issue now.
