### ISSUE TITLE
rateLimit not working

### ISSUE THREAD

**Issue by FabriceGaudin** [andris9/nodemailer-ses-transport#17]
My rateLimit with Amazon SES is 14 mails/s, but if I set a rateLimit equals to 14 in the ses transport, I get `Maximum sending rate exceeded` errors. However if I set the rateLimit to 10, I don't have any error.
Do you know if it's a lack of precision or does the problem come from Amazon SES ?

**Comment by massimocode** [comment]
@FabriceGaudin how comes you closed this issue?

**Comment by FabriceGaudin** [comment]
@massimocode With this PR: https://github.com/andris9/nodemailer-ses-transport/pull/18, now it's working fine for me

**Comment by massimocode** [comment]
Yep I see how it's being done. I was looking a the source code and was going to say it looks like it could never be a problem, I didn't notice it came from your PR! Thanks!
