### ISSUE TITLE
Rate limiting on a bad connection

### ISSUE THREAD

**Issue by massimocode** [andris9/nodemailer-ses-transport#20]
I've been trying to use this on a poor connection (300-400ms ping time to google.com) for sending a couple of thousand emails. I have set a rate limit of 5 (which works fine with a small list of email addresses) but with a list of several thousand it fails.

I wanted to spend some time documenting the way the rate limit works and put in a PR for that, but since using it on this connection I've come to the conclusion that the current implementation isn't really ideal. It might work for solid reliable connections with low ping times, but it can really mess up on useless/intermittent connections. I start getting Amazon timeouts and not sure if the recipients are receiving the emails twice.

I suggest we take another look at the rate limiting implementation. If I get time I'll put in a PR for an alternative implementation that will throttle based on the user's connection quality (meaning no issue for most users, but throttling for those with bad connections). What do you guys think? @FabriceGaudin @andris9

**Comment by massimocode** [comment]
I remember now how I implemented this in C# (I have a nice rock solid C# mailer but moving over to a JS one cause I do more JS dev these days).

I was using 2 threads per mail per second. So if the rate limit was 5, then I would spin up 10 threads. They would read off a shared array of email addresses and send emails. Each thread would get "permission to send" from a shared clock, waiting if necessary.

Now the thing I am thinking is that perhaps we should keep a count of how many operations are "in flight" and only allow 2 or 3 times the number of rate limit.

I will give it a go and let you know how it works out for me.

**Comment by massimocode** [comment]
ok turns out I am still using v1.3.1 and I don't think a newer version has been published on NPM

**Comment by massimocode** [comment]
I grabbed the latest version from github and replaced the one in my node_modules version. It seems much much more reliable. However, I do still think that it's worth including the aforementioned throttle if the user's connection can't handle the rate limit they set. If you guys are ok with it let me know and I'll put in a PR. I don't see it affecting performance of people with strong enough connections in any way. It will only stop connection suffocation for people with weaker connections.

**Comment by massimocode** [comment]
After quite a lot of testing I've put in a PR for this: https://github.com/andris9/nodemailer-ses-transport/pull/21

**Comment by andris9** [comment]
Merged and released as v1.4.0
