### ISSUE TITLE
SMTP envelope ignored

### ISSUE THREAD

**Issue by willmcenaney** [andris9/nodemailer-ses-transport#22]
Pretty awesome implementation all round, but for our purposes I need to be able to handle the SMTP message splitting on my server.  i.e. The recipients are each sent a separate message with the correct recipients headers (only goes to one recipient but appears to come from many).  I know it sounds nefarious, but essentially i'm running a verification on emails so I need to split off who i'm emailing.

On my local copy I am passing in an awsRecipients array which is added to params as Destinations on handleMessage.  I presume that using the nodemailer envelope would be better for a robust implementation?  It should concatenate any envelope to,cc,and bcc fields if present, else leave out.

Cheers
Will

**Comment by andris9** [comment]
If you want to use the envelope option then you should use SES over SMTP and not through the API.

**Comment by willmcenaney** [comment]
It is supported by the Api. I have it working.

Thanks

**Comment by andris9** [comment]
In general I have nothing against adding envelope support to ses transport as well but I don't have time for this myself, so maybe you would like to jump in and make a PR for it? The behavior should remain the same as in SMTP – envelope overrides all from and recipient addresses without modifying the actual rfc822 message.

**Comment by willmcenaney** [comment]
I'll consider it. Would be good not to have to diverge from your trunk
longterm :-)

Thanks
