### ISSUE TITLE
Incorrect Endpoint Generated

### ISSUE THREAD

**Issue by nollieheel** [andris9/nodemailer-ses-transport#25]
Good day,

I have this configuration:

```
var nodemailer = require('nodemailer');
var ses = require('nodemailer-ses-transport');

var tp = nodemailer.createTransport(ses({
  accessKeyId: 'XXXXX',
  secretAccessKey: 'YYYY',
  region: 'us-west-2'
}));
```

I might be doing something wrong, but that gives me an error:

```
The Canonical String for this request should have been
'POST
/

host:email.us-west-2.amazonaws.com
x-amz-content-sha256:xxxxxxxxxxxxxxxxxxxxxxx
x-amz-date:20160916T122437Z

host;x-amz-content-sha256;x-amz-date
xxxxxxxxxxxxxxxxxxxxxxx'
```

In my AWS SES account, the endpoint is actually `email-smtp.us-west-2.amazonaws.com`, which is different from `host` value generated above.

I tried adding this line in my transport config:

```
ServiceUrl: 'email-smtp.us-west-2.amazonaws.com',
```

but the result is the same.

Hoping to get some advise on this. Thanks.

In the meantime, I'm just using the standard nodemailer (no plugin) format of 'smtps://user:pass@endpoint', which works fine.

**Comment by eberls** [comment]
I ran into this too, and in order to get things functional ended up using:
```
var transport = nodemailer.createTransport({
        transport: "smtp",
        host: "email-smtp.us-west-2.amazonaws.com",
        secureConnection: true,
        port: 465,
        auth: {
            user: config.app.ses_accessKey,
            pass: config.app.ses_secretKey
        }
    });
```


Is the SES transport just fundamentally broken?

**Comment by jazzominy** [comment]
@eberls Thanks for the updated. I was facing the same issue. Your solution worked for me
