### ISSUE TITLE
Improve error handling support

### ISSUE THREAD

**Issue by markstos** [andris9/nodemailer-ses-transport#4]
Thanks for this module.

Right now I don't see any docs or test around error handling.

From what I understand, Amazon will return XML in case of an error and this module will pass that through to the user. 

I think it would be more node-ish is module parsed the XML and returned JSON instead. No matter the error handling behavior, some tests and docs to clarify what's happening with error handling would be welcome, especially since the SES REST API returns errors as XML.

**Comment by rightaway** [comment]
@markstos Are you parsing the XML errors yourself, or how are you handling them in general (like for determining how your application should respond)?

**Comment by markstos** [comment]
@rightaway Right now I use [node-ses](https://github.com/aheckmann/node-ses) instead of this module, which uses `xml2js` to convert Amazon's XML resposnes to JavaScript objects.  It's simple and pleasant to use. I was evaluating this module as a replacement, but currently have no problems with `node-ses` as a solution.
