### ISSUE TITLE
Nothing happens

### ISSUE THREAD

**Issue by mattfiocca** [andris9/nodemailer-ses-transport#6]
Hi, i can confirm that my SES account is working properly, can send test emails just fine, but when i try this node module, i get no response, no errors, and no sent email. I'm sending to and from my verified addresses in my SES account. Here's my usage:

test.js:

``` javascript
var nodemailer = require('nodemailer');
var ses = require('nodemailer-ses-transport');
var transporter = nodemailer.createTransport(ses({
    accessKeyId: "<KEY>",
    secretAccessKey: "<SECRET>"
}));
transporter.sendMail({
    from: 'matt.fiocca@gmail.com', // verified in SES
    to: 'matt@snapdragon.is', // verified in SES
    subject: 'Render Job Complete',
    text: 'Rendering has completed for job# ' + 23
});
```

Called with:
`$ node test.js`

```
$ node -v
$ v0.10.33
```

```
$ cat package.json
{
  "name": "renderfarm-worker",
  "description": "Snapdragon Renderfarm Worker",
  "version": "0.0.1",
  "private": true,
  "dependencies": {
    "carrier": "*",
    "mysql": "*",
    "nodemailer": "^1.3.0",
    "nodemailer-ses-transport": "^1.2.0",
    "sleep": "*",
    "validator": "*"
  }
}
```

**Comment by molinto** [comment]
Did you figure this out @mattfiocca?

**Comment by mattfiocca** [comment]
@molinto, I have not. Its been a while though, and i had moved on, using a combo of the aws-sdk and mailcomposer modules to work with SES.

**Comment by molinto** [comment]
Ok thanks buddy

**Comment by acao** [comment]
I'm in the same boat as @mattfiocca here. Don't want to have to work around this.

**Comment by bentedder** [comment]
I'm in a similar place, except getting "MessageRejected: Email address is not verified" even though I have a verified domain and email (no-reply@xyz.com)

**Comment by bentedder** [comment]
Updating to say that all I was missing was the 'region' key in my transporter settings. default was not the same as what my account was approved for. Hope it helps somebody else!

**Comment by ksibod** [comment]
@bentedder Thank you for that - setting the `region` was my problem as well.
