### ISSUE TITLE
SES has a limit of 50 recipients per email

### ISSUE THREAD

**Issue by angelo0000** [andris9/nodemailer-ses-transport#8]
It would be nice if this transport would break up the email to allow for sending an email to more than 50 recipients transparently. This seems like a feature the transport should provide.

**Comment by andris9** [comment]
Sending messages in chunks would mean that for every chunk there would be separate action that can either fail or succeed. So if I send 200 messages it would make 4 different transactions and if two of these fails the `sendMail` callback should return 2 error messages and 1 combined success message for the succeed transactions. I think this would make the API too complicated as you'd have to start checking which messages failed and why. Besides it is bad practice to send bcc emails anyway, I don't see a reason not to send a single message to single recipient – after all SES charges you for the count of recipients, not for the count of messages.

**Comment by angelo0000** [comment]
That actually makes total sense.  Thanks for taking the time to explain.
